
name: Build

on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m venv testenv
        . testenv/bin/activate
        python -m pip install --upgrade pip setuptools
        python -m pip install git+https://github.com/radical-cybertools/radical.utils.git@devel
        python -m pip install --upgrade .
        python -m pip install -r requirements-tests.txt
    - name: Run tests
      run: |
        . testenv/bin/activate
        coverage run --source=radical.dreamer -m pytest -ra --timeout=600 -vvv --showlocals tests/unit_tests/
        coverage xml
    - uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml

  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m venv testenv
        . testenv/bin/activate
        python -m pip install --upgrade pip setuptools
        python -m pip install git+https://github.com/radical-cybertools/radical.utils.git@devel
        python -m pip install --upgrade .
        python -m pip install -r requirements-tests.txt
    - name: Lint with flake8 and pylint
      run: |
        . testenv/bin/activate
        LOG=`git log -n 1 | grep Merge || true`
        NEW=`echo $LOG | cut -d ' ' -f2`
        OLD=`echo $LOG | cut -d ' ' -f3`
        test -z "$NEW" && NEW=HEAD
        test -z "$OLD" && OLD=HEAD
        DIFF=`git diff  --name-only --diff-filter=db $NEW..$OLD`
        DIFF=$(echo $DIFF | grep -o -e '\b[^ ]*.py\b' | sed "s|^|$PWD/|")
        test -z "$DIFF" && echo 'nothing to flake8' || flake8 $DIFF
        test -z "$DIFF" && echo 'nothing to pylint' || pylint $DIFF
